# See https://github.com/vgteam/long-read-giraffe-experiments/blob/main/lr-config.yaml
# This is a simplified file based on the above

real_slurm_extra: "--exclude=phoenix-[00-10,22-24]"
exclusive_timing: true
min_exclusive_reads: 1000000
# Note that reserving a full node is the only way we have to ensure a job is not split across NUMA nodes

experiments:

  compare_variant_calling:
    control:
      subset: full
      reference: chm13
      sample: HG002
      realness: real
      refgraph: hprc-v2.1-mc-eval-sampled16os
      # SV specific parameters with generic names
      caller: vgcall
      truthset: giab6
      truthref: chm13
    vary:
      tech: ["r10y2025", "hifi"]
      mapper: ["giraffe-k31.w50.W-hifi-00bf3b-noflags", "giraffe-k31.w50.W-hifi-18f9eb-noflags", "giraffe-k31.w50.W-r10-00bf3b-noflags", "giraffe-k31.w50.W-r10-18f9eb-noflags"]
    constrain:
      - tech: "hifi"
        mapper: ["giraffe-k31.w50.W-hifi-00bf3b-noflags", "giraffe-k31.w50.W-hifi-18f9eb-noflags"]
      - tech: "r10y2025"
        mapper: ["giraffe-k31.w50.W-r10-00bf3b-noflags", "giraffe-k31.w50.W-r10-18f9eb-noflags"]